
#include "minishell.h"

int	g_sigint = 0;

static void	signal_processing1(int sig)
{
	if (sig == SIGINT)
	{
		g_sigint = SIGINT;
		write(2, "\n", 1);
		rl_on_new_line();
		rl_replace_line("", 0);
		rl_redisplay();
	}
}
static void	signal_processing2(int sig)
{
	if (sig == SIGINT)
		g_sigint = SIGINT;
}
static void	signal_processing3(int sig)
{
	if (sig == SIGINT)
	{
		g_sigint = SIGINT;
		write(2, "\n", 1);
		rl_on_new_line();
		rl_replace_line("", 0);
	}
}

void signals(int mode)
{
	if (mode == 1) //interactive
	{
		signal(SIGINT, &signal_processing1);
		signal(SIGQUIT, SIG_IGN);
	}
	else if (mode == 2) //non-interactive (basically parent)
	{
		signal(SIGINT, &signal_processing2);
		signal(SIGQUIT, SIG_DFL);
	}
	else if (mode == 3) //heredoc
	{
		signal(SIGINT, &signal_processing3);
		signal(SIGQUIT, SIG_IGN);
	}
	/* else if (mode == 4) //child (we probably don't even need it)
	{
		signal(SIGINT, SIG_DFL);
		signal(SIGQUIT, SIG_DFL);
	} */
	/* else if (signal(SIGQUIT, SIG_IGN))
		perror("Ctrl-\\"); */
	// signal(SIGINT, signal_processing); // SIGINT is a signal generated by pressing Ctrl+C
	// signal(SIGQUIT, signal_processing); /* SIGQUIT is a signal generated by pressing Ctrl+\ */
	// signal(SIGTERM, signal_processing); // SIGTERM is a signal generated by the "kill" command
	// signal(SIGTSTP, signal_processing); // SIGTSTP is a signal generated by pressing Ctrl+Z
}