
#include "minishell.h"

// static void	signal_processing(int sig)
// {
// 	if (sig == SIGINT)
// 	{
// 		printf("\n");
// 		rl_on_new_line();
// 		rl_replace_line("~/minishell>", 0);
// 	}
// 	else if (sig == SIGQUIT)
// 	{
// 		printf("\n");
// 		rl_on_new_line();
// 	}
// 	else if (sig == SIGTERM)
// 	{
// 		printf("\n");
// 		rl_on_new_line();
// 	}
// 	else if (sig == SIGTSTP)
// 	{
// 		printf("\n");
// 		rl_on_new_line();
// 	}
// 	else
// 		return ;
// }

// void signals(void)
// {
// 	signal(SIGINT, signal_processing); // SIGINT is a signal generated by pressing Ctrl+C
// 	signal(SIGQUIT, signal_processing); /* SIGQUIT is a signal generated by pressing Ctrl+\ */
// 	signal(SIGTERM, signal_processing); // SIGTERM is a signal generated by the "kill" command
// 	signal(SIGTSTP, signal_processing); // SIGTSTP is a signal generated by pressing Ctrl+Z
// }